name: Code Formatter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - run: black --check .
      - name: Commit black changes
        if: failure()
        run: |
          echo "Need to be formatted."